version: 11.7.1.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova.ArvatoPaymentGateway
  sonarcloudkey:
    secure: 0VvcxYCPLglmyB87e5B1vRk0nHq8KUX0ND/qLkCs1RaGULzo1Q+XPHOZgioTbEPZ
  testFilter: Category!=Integration&Category!=Manual
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
- ps: >-
    If ("$env:sonarcloudkey".Length -gt 0) {
      choco install sonarscanner-msbuild-net46 dotcover-cli -y --no-progress
      SonarScanner.MSBuild.exe begin /k:"$env:sonarcloudproj" /d:"sonar.host.url=https://sonarcloud.io" /o:"$env:sonarcloudorg" /d:"sonar.branch.name=$env:APPVEYOR_REPO_BRANCH" /d:"sonar.login=$env:sonarcloudkey" /d:sonar.cs.dotcover.reportsPaths="$env:APPVEYOR_BUILD_FOLDER\dotcover.html" /d:sonar.cs.xunit.reportsPaths="$env:APPVEYOR_BUILD_FOLDER\xunit.xml"
    }
after_test:
- cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- cmd: IF DEFINED sonarcloudkey (OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test --no-build -c %configuration% -l \"trx;LogFileName=%APPVEYOR_BUILD_FOLDER%\test.results.xml\" --filter %testFilter%" -output:%APPVEYOR_BUILD_FOLDER%\opencover.results.xml -coverbytest:*Tests.dll -oldStyle) ELSE (dotnet test --no-build -c %configuration% --filter "%testFilter%")
cache:
  - '%USERPROFILE%\.nuget\packages'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
deploy:
  provider: NuGet
  api_key:
    secure: 6LdiQeX2LTezBZsshcBSJ2oUqVNDPkKj4y2VpHiM+wtg86SAJd/hzJl0mgavblhr
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_BRANCH: master
