version: 11.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova_Epinova.ArvatoPaymentGateway
  sonarcloudkey:
    secure: xxxxxxxxxxxxxxxxxxxxxx
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
after_build:
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
  - path: '**\xunit*.xml'

test_script:
- cmd: 'OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.exe" -targetargs:"tests\bin\Release\Epinova.ArvatoPaymentGatewayTests.dll -xml xunit.test.results.xml -appveyor" -output:xunit.opencover.xml -coverbytest:*.Tests.dll'

#test:
#  categories:
#    except:
#    - Integration
#    - Manual

cache:
  - packages -> **\packages.config
  - '%ProgramData%\chocolatey\lib\'
  
deploy:
  provider: NuGet
  api_key:
    secure: ZZbW4ozun1BxPT+nDSKv6rBtWGE4z5t+iRWcpiZ9GPlUWqYI/x5wXnCaKK10VRkz
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: masterz
    APPVEYOR_REPO_BRANCH: master

# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  before_build:
  - cmd: nuget restore
  - cmd: IF DEFINED sonarcloudkey choco install sonarscanner-msbuild-net46 opencover.portable -y && SonarScanner.MSBuild.exe begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.login=%sonarcloudkey%" /d:sonar.cs.opencover.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.opencover.xml" /d:sonar.cs.xunit.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.test.results.xml"
  after_test:
  - cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
